apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-west-2a/EBS-VOLUME-ID-HERE
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem