apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        ports:
        - containerPort: 80
      - name: wordpress
        image: wordpress:php8.0-fpm-alpine
        lifecycle:
          postStart:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  until [ -f /var/www/html/wp-config.php ]
                  do
                  sleep 5
                  done
                  #update the wp-config.php
                  sed -i "86idefine('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL); #k8s.v2" /var/www/html/wp-config.php
                  exit
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-config
              key: host
        - name: WORDPRESS_DB_PORT
          value: "3306"
        - name: WORDPRESS_DB_USER
          value: "admin"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-config
              key: password
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        ports:
        - containerPort: 9000
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-conf      
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
